apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-java-app
  template:
    metadata:
      labels:
        app: devops-java-app
    spec:
      containers:
      - name: devops-java-app
        image: ayush529/devops-java-app:latest   # ðŸ‘ˆ your Docker Hub image name
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devops-java-service
spec:
  type: NodePort
  selector:
    app: devops-java-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
